# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgb_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rgb_image.proto',
  package='ai_powered_visual_inspection_for_manifacturing',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0frgb_image.proto\x12.ai_powered_visual_inspection_for_manifacturing\"V\n\tRGB_image\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x01(\x0c\"\xa3\x01\n\tPredicted\x12\r\n\x05label\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x14\n\x0cheight_image\x18\x06 \x01(\x05\x12\x13\n\x0bwidth_image\x18\x07 \x01(\x05\x12\x13\n\x0b\x64\x65pth_image\x18\x08 \x01(\x05\x12\x12\n\nconfidence\x18\t \x01(\x02\x32\x92\x01\n\x0fPredict_service\x12\x7f\n\x07Predict\x12\x39.ai_powered_visual_inspection_for_manifacturing.RGB_image\x1a\x39.ai_powered_visual_inspection_for_manifacturing.Predictedb\x06proto3'
)




_RGB_IMAGE = _descriptor.Descriptor(
  name='RGB_image',
  full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.depth', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.image', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=153,
)


_PREDICTED = _descriptor.Descriptor(
  name='Predicted',
  full_name='ai_powered_visual_inspection_for_manifacturing.Predicted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.width', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.height', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height_image', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.height_image', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width_image', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.width_image', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.depth_image', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ai_powered_visual_inspection_for_manifacturing.Predicted.confidence', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=319,
)

DESCRIPTOR.message_types_by_name['RGB_image'] = _RGB_IMAGE
DESCRIPTOR.message_types_by_name['Predicted'] = _PREDICTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RGB_image = _reflection.GeneratedProtocolMessageType('RGB_image', (_message.Message,), {
  'DESCRIPTOR' : _RGB_IMAGE,
  '__module__' : 'rgb_image_pb2'
  # @@protoc_insertion_point(class_scope:ai_powered_visual_inspection_for_manifacturing.RGB_image)
  })
_sym_db.RegisterMessage(RGB_image)

Predicted = _reflection.GeneratedProtocolMessageType('Predicted', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTED,
  '__module__' : 'rgb_image_pb2'
  # @@protoc_insertion_point(class_scope:ai_powered_visual_inspection_for_manifacturing.Predicted)
  })
_sym_db.RegisterMessage(Predicted)



_PREDICT_SERVICE = _descriptor.ServiceDescriptor(
  name='Predict_service',
  full_name='ai_powered_visual_inspection_for_manifacturing.Predict_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=322,
  serialized_end=468,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='ai_powered_visual_inspection_for_manifacturing.Predict_service.Predict',
    index=0,
    containing_service=None,
    input_type=_RGB_IMAGE,
    output_type=_PREDICTED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICT_SERVICE)

DESCRIPTOR.services_by_name['Predict_service'] = _PREDICT_SERVICE

# @@protoc_insertion_point(module_scope)
